# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
gem 'rake'
require 'rest_client'
require 'json'
gem 'rest-client', '~> 2.0', '>= 2.0.2'
# gem 'activerecord'
